<?xml version="1.0"?>
<package format="3">
  <name>cube_swapper</name>
  <version>0.0.0</version>
  <description>MoveIt pipeline: pick cube at red tag and place at blue tag</description>

  <maintainer email="prakash@todo.todo">prakash</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

